const TYPES_PRODUCTROUTE = {
  productData: "product-data",
  error: "error",
  loadingProduct: "loading-product",
  loadingComments: "loading-comments",
  loadingSimilarProducts: "loading-similar-products",
  loadingReputationSeller: "loading-reputation-seller",
  loadingFavOperation: "loading-fav",
  commentsData: "comments-data",
  backPageComment: "back-page-comment",
  nextPageComment: "next-page-comment",
  similarProductsData: "similar-products-data",
  sellerProductsData: "seller-products-data",
  reputationsSellerData: "reputation-seller-data",
  setFavorites: "set-favorites-products",
  addNewFavorite: "add-favorites",
  removeOneFavorite: "remove-favorite",
  handleChangeComment: "handle-change-comment",
  errorFormComment: "error-form-comment",
  addNewComment: "add-new-comment",
};
export default TYPES_PRODUCTROUTE;
